#!/usr/bin/python

import argparse
import os.path
import subprocess


def main():
    parser = argparse.ArgumentParser(description="Simple driver for pandoc. Or use pandoc directly for more options.")
    parser.add_argument("source", help="Source markdown file")
    args = parser.parse_args()
    output = os.path.splitext(args.source)[0] + ".pdf"
    pan_args = ["pandoc", "-f", "markdown", "-V", "theme:Dresden"] #Edit this if not in Heather's Group
    # Add some args here, for those wanting to make this better for extra credit
    pan_args.extend(["--write", "beamer", "--template", "talk.beamer", "-o", output, args.source])
    print "Executing:", " ".join(pan_args)
    subprocess.check_call(pan_args)


if __name__ == "__main__":
    main()

